### ISSUE TITLE
Build command and pub transforms

### ISSUE THREAD

**Issue by Hecatoncheir** [dart-bridge/framework#36]
Hi. If I get it right, build command for compile .dart to .js files. But how i can apply transformers like sass or polymer? With that transformers in pubspec:

```
transformers:
  - sass:
      compass: true
      style: compact
      copy-sources: false
  - polymer:
      entry_points: lib/server/templates/main.html
```

pub get return error from ScriptCompactor:

```
[Warning from polymer (Linter) on masatake|lib/server/templates/error.html]:
line 1, column 1 of lib/server/templates/error.html: (from html) Unexpected non-space characters. Expected DOCTYPE. See http://goo.gl/5HPeuP#polymer_40 for details.
@extends ('base')
^^^^^^^^^^^^^^^^^
Build failed.
```

and sass files does not compile too. But if i can add some sass compile command with @Command, how make it for polymer?

It would be great, if the build command could be apply a transformers from pubspec.

**Comment by emilniklas** [comment]
Hi!

I agree that the build command should include transformers. 

However, Polymer.dart assumes A LOT, to be able to support html imports, so it's hard to combine their transformer with Bridge's templates. Currently, the way to do this is to simply stop using Bridge templates, and conforming to the Polymer way (html files in web/) and change the config key for the publicly served directory from web/ to build/web/.

Then, to serve up the correct html file, simply return a normal file read in the route:

``` dart
router.get('/', () => new File('build/web/index.html').readFileAsString());
```

Or even better, to not read the file on every request:

``` dart
final index = await new File('build/web/index.html').readFileAsString();

router.get('/', () => index);
```

**Comment by Hecatoncheir** [comment]
Yes, I did it. Now it work. Thanks.

**Comment by emilniklas** [comment]
The build command now runs `pub build`. However, due to an issue with `pub` and `dart2js`, JavaScript compilation is run manually. To ignore dart files in pub build, this has to be injected in `pubspec`:

``` yaml
# Temporary (https://github.com/dart-lang/pub/issues/1341)
transformers:
- $dart2js:
    $exclude: web/**.dart
```
